### PR TITLE
WIP: MLR-509

### PR DESCRIPTION
**Pull request by cschroed-usgs**
One way this could be implemented is sketched out in this pull request. The main idea is to move as much of the caching logic outside of the app as possible so that the app can be simpler. I tried to illustrate this by reorganizing ref lists so they look like this...
```
references/
├── local
│   ├── site_type_cross_field.json
│   ├── site_type_invalid.json
│   └── site_type_transition.json
└── remote
    ├── aquifer.json
    ├── county.json
    ├── huc.json
    ├── land_net.json
    ├── mcd.json
    ├── national_aquifer.json
    ├── national_water_use.json
    ├── reference_lists.json
    ├── site_number_format.json
    └── state.json
```

Local ref lists are checked into the repo and included in the docker image. Remote ref lists are not included in either. Instead, remote reference lists are retrieved via a cron job that runs `aws s3 sync` every N minutes. Having the validation services read a local dir each time the API is hit probably is faster than pulling everything from S3. This approach doesn't require the python portion of the app to manage expiration times, S3 retrievals, or retry logic. This approach would enable validations to continue even if S3 were intermittently unavailable.

It's not all roses. The hard parts are still ahead on this approach -- figuring out modifications to the  Dockerfile, docker-compose.yml's, chef config, and/or cloudformation templates.

Before I head down that road, I'd like a lil sanity check :)

### CODE REVIEW

**Comment by cschroed-usgs** [comment]
Also, many of the approaches for this ticket could require us to move to GitLab so that CI/CD would be able to pull the external ref lists out of S3.

**Comment by zmoore-usgs** [comment]
I'll take a look at this after my 10-11 meeting this morning

**Comment by kmschoep-usgs** [comment]
I'm wondering if since this approach relies on caching so that it's truly not pulling from S3 in real time, would be easier or more straightforward to just have these pulled in a build time instead of running an S3 sync job every n seconds/minutes?  These lists are only updated every 3 months (at least until RLMS is up and running, in which case they could conceivably be updated more frequently, but we don't know what state MLR will be in at that point, either), so having a rebuild and short outage to refresh the ref lists doesn't seem like a huge burden.

**Comment by zmoore-usgs** [comment]
Overall as far as this method goes I like offloading the responsibility of pulling from S3 to something other than the application itself in order to help keep things simple in the application. I think the reorganization of the reference lists into `local` and `remote` makes sense.

My initial thought would be that we don't necessarily want to add learning how to kick off a build to Operations' plate, but at the same time it isn't that much different than running other jobs. Perhaps something like how DECAP currently handles pulling its config files from S3 could work?

What if we have Chef pull the list directory from S3 each time it runs (like DECAP does with its configuration) and then have the directory on EC2 that it pulls them into volume mounted into the Validator container? That would remove the need for cron in the container itself and we could leverage the existing Chef runs to do the S3 syncing and then just mount it like we mount existing configuration files in the container.

**Comment by cschroed-usgs** [comment]
@kmschoep-usgs thanks for thinking big! I ported the conversation over to the epic in JIRA.

**Comment by cschroed-usgs** [comment]
@zmoore-usgs I like the idea of eschewing a custom cron job in favor of leveraging the existing ~15 minute chef run to sync the files -- one less concern for the container to worry about!

**Pull request closed without merging**
